# Generated by Django 5.2.1 on 2025-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrition_facts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
